# Generated by Django 5.0.4 on 2024-05-17 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibeapp', '0003_blockeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='VibeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_vibe', models.BooleanField(default=False)),
                ('user2_vibe', models.BooleanField(default=False)),
                ('matched', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibe_match_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibe_match_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
